"""testing

Revision ID: 22eaa04ccf35
Revises: c091fdd43825
Create Date: 2023-02-23 23:18:52.766181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22eaa04ccf35'
down_revision = 'c091fdd43825'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
