"""upgrage user and post field

Revision ID: 5fd221687d3b
Revises: 46f91b2e38cc
Create Date: 2023-03-04 17:13:26.455792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fd221687d3b'
down_revision = '46f91b2e38cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
