"""testing

Revision ID: c091fdd43825
Revises: 12d2b42b9617
Create Date: 2023-02-23 23:16:35.993444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c091fdd43825'
down_revision = '12d2b42b9617'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('username', sa.String(length=125), nullable=False))
    op.add_column('User', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('User', sa.Column('password', sa.String(length=128), nullable=False))
    op.create_unique_constraint(None, 'User', ['email'])
    op.create_unique_constraint(None, 'User', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='unique')
    op.drop_constraint(None, 'User', type_='unique')
    op.drop_column('User', 'password')
    op.drop_column('User', 'email')
    op.drop_column('User', 'username')
    # ### end Alembic commands ###
