"""upgrage user model

Revision ID: 067bb8fec2ca
Revises: 4ce74a11f7f4
Create Date: 2023-03-06 22:46:31.576655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '067bb8fec2ca'
down_revision = '4ce74a11f7f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
