"""upgrage user and post field

Revision ID: 46f91b2e38cc
Revises: 74fdd15aa008
Create Date: 2023-03-04 17:02:48.995382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46f91b2e38cc'
down_revision = '74fdd15aa008'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
