"""upgrage post model

Revision ID: 4ce74a11f7f4
Revises: 5fd221687d3b
Create Date: 2023-03-04 19:54:51.265736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ce74a11f7f4'
down_revision = '5fd221687d3b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('post_table_author_id_fkey', 'post_table', type_='foreignkey')
    op.create_foreign_key(None, 'post_table', 'user_table', ['author_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_table', type_='foreignkey')
    op.create_foreign_key('post_table_author_id_fkey', 'post_table', 'user_table', ['author_id'], ['id'])
    # ### end Alembic commands ###
